(cl:defpackage part_fetcher-msg
  (:use )
  (:export
   "<PARTFETCHERRESULT>"
   "PARTFETCHERRESULT"
   "<PARTFETCHERGOAL>"
   "PARTFETCHERGOAL"
   "<PARTFETCHERACTIONRESULT>"
   "PARTFETCHERACTIONRESULT"
   "<PARTFETCHERACTIONGOAL>"
   "PARTFETCHERACTIONGOAL"
   "<PARTFETCHERFEEDBACK>"
   "PARTFETCHERFEEDBACK"
   "<PARTFETCHERACTIONFEEDBACK>"
   "PARTFETCHERACTIONFEEDBACK"
   "<PARTFETCHERACTION>"
   "PARTFETCHERACTION"
  ))

