// Generated by gencpp from file final_lab/path.msg
// DO NOT EDIT!


#ifndef FINAL_LAB_MESSAGE_PATH_H
#define FINAL_LAB_MESSAGE_PATH_H

#include <ros/service_traits.h>


#include <final_lab/pathRequest.h>
#include <final_lab/pathResponse.h>


namespace final_lab
{

struct path
{

typedef pathRequest Request;
typedef pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct path
} // namespace final_lab


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::final_lab::path > {
  static const char* value()
  {
    return "87fbad184f990f6671a31d6fd2678f60";
  }

  static const char* value(const ::final_lab::path&) { return value(); }
};

template<>
struct DataType< ::final_lab::path > {
  static const char* value()
  {
    return "final_lab/path";
  }

  static const char* value(const ::final_lab::path&) { return value(); }
};


// service_traits::MD5Sum< ::final_lab::pathRequest> should match 
// service_traits::MD5Sum< ::final_lab::path > 
template<>
struct MD5Sum< ::final_lab::pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::final_lab::path >::value();
  }
  static const char* value(const ::final_lab::pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::final_lab::pathRequest> should match 
// service_traits::DataType< ::final_lab::path > 
template<>
struct DataType< ::final_lab::pathRequest>
{
  static const char* value()
  {
    return DataType< ::final_lab::path >::value();
  }
  static const char* value(const ::final_lab::pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::final_lab::pathResponse> should match 
// service_traits::MD5Sum< ::final_lab::path > 
template<>
struct MD5Sum< ::final_lab::pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::final_lab::path >::value();
  }
  static const char* value(const ::final_lab::pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::final_lab::pathResponse> should match 
// service_traits::DataType< ::final_lab::path > 
template<>
struct DataType< ::final_lab::pathResponse>
{
  static const char* value()
  {
    return DataType< ::final_lab::path >::value();
  }
  static const char* value(const ::final_lab::pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FINAL_LAB_MESSAGE_PATH_H
