(cl:defpackage my_action_server-msg
  (:use )
  (:export
   "<DEMO2ACTION>"
   "DEMO2ACTION"
   "<DEMO2ACTIONFEEDBACK>"
   "DEMO2ACTIONFEEDBACK"
   "<DEMO2FEEDBACK>"
   "DEMO2FEEDBACK"
   "<DEMO2RESULT>"
   "DEMO2RESULT"
   "<DEMO2ACTIONGOAL>"
   "DEMO2ACTIONGOAL"
   "<DEMO2GOAL>"
   "DEMO2GOAL"
   "<DEMO2ACTIONRESULT>"
   "DEMO2ACTIONRESULT"
  ))

