; Auto-generated. Do not edit!


(cl:in-package my_action_server-msg)


;//! \htmlinclude demo2Feedback.msg.html

(cl:defclass <demo2Feedback> (roslisp-msg-protocol:ros-message)
  ((fdbk
    :reader fdbk
    :initarg :fdbk
    :type cl:integer
    :initform 0))
)

(cl:defclass demo2Feedback (<demo2Feedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <demo2Feedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'demo2Feedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name my_action_server-msg:<demo2Feedback> is deprecated: use my_action_server-msg:demo2Feedback instead.")))

(cl:ensure-generic-function 'fdbk-val :lambda-list '(m))
(cl:defmethod fdbk-val ((m <demo2Feedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader my_action_server-msg:fdbk-val is deprecated.  Use my_action_server-msg:fdbk instead.")
  (fdbk m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <demo2Feedback>) ostream)
  "Serializes a message object of type '<demo2Feedback>"
  (cl:let* ((signed (cl:slot-value msg 'fdbk)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <demo2Feedback>) istream)
  "Deserializes a message object of type '<demo2Feedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'fdbk) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<demo2Feedback>)))
  "Returns string type for a message object of type '<demo2Feedback>"
  "my_action_server/demo2Feedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'demo2Feedback)))
  "Returns string type for a message object of type 'demo2Feedback"
  "my_action_server/demo2Feedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<demo2Feedback>)))
  "Returns md5sum for a message object of type '<demo2Feedback>"
  "46cc8f8da6ebf35aedc6bad2e96b2e59")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'demo2Feedback)))
  "Returns md5sum for a message object of type 'demo2Feedback"
  "46cc8f8da6ebf35aedc6bad2e96b2e59")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<demo2Feedback>)))
  "Returns full string definition for message of type '<demo2Feedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 fdbk~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'demo2Feedback)))
  "Returns full string definition for message of type 'demo2Feedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 fdbk~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <demo2Feedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <demo2Feedback>))
  "Converts a ROS message object to a list"
  (cl:list 'demo2Feedback
    (cl:cons ':fdbk (fdbk msg))
))
