(cl:defpackage object_finder-msg
  (:use )
  (:export
   "<OBJECTFINDERACTIONFEEDBACK>"
   "OBJECTFINDERACTIONFEEDBACK"
   "<OBJECTFINDERACTIONGOAL>"
   "OBJECTFINDERACTIONGOAL"
   "<OBJECTFINDERACTION>"
   "OBJECTFINDERACTION"
   "<OBJECTFINDERRESULT>"
   "OBJECTFINDERRESULT"
   "<OBJECTFINDERGOAL>"
   "OBJECTFINDERGOAL"
   "<OBJECTFINDERFEEDBACK>"
   "OBJECTFINDERFEEDBACK"
   "<OBJECTFINDERACTIONRESULT>"
   "OBJECTFINDERACTIONRESULT"
  ))

